Error handling with promises 
Promises are used for managing the execution flow in a program. Chaining Promises is also useful when executing a series of asynchronous functions, where each depends on the prior function. In a Promise, you can utilize two methods for handling errors which are the “then()” method and the “catch()” block.
JavaScript Promise Error Handling using then() method

JavaScript Promise Error Handling using catch() block
Using the catch() and then() methods, you can handle the error thrown or reject() call in Promise Chaining. To handle errors, it is preferable to add a catch() method in your code. The error handler then examines the code and handles them accordingly.
https://javascript.info/promise-error-handling
